helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

Add following annotations to ingress 
```
nginx.ingress.kubernetes.io/proxy-body-size
nginx.ingress.kubernetes.io/proxy-read-timeout
```
For uploads greater than 1 MB.

cd: Update Ingress [PAGOPA-1399]

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java

Return `STATUS` if already exists.
It may happen that the function consumes the event before the `STATUS` is created by the micro-service. So the micro-service already finds the instance of the `STATUS` present in the database.

fix: Saving conflict handling

---

.identity/env/prod/backend.tfvars
.identity/env/uat/backend.tfvars

chore: Fix cfg identity

---

.github/workflows/integration_test.yml
integration-test/src/step_definitions/support/data.js

- refactoring on data to identify test data
- refactoring action: delete prod option

chore: update integration test configuration [PAGOPA-1364]

---

integration-test/src/features/upload-report.feature

only integration test was involved in this change
- reduce integration test payment position size from `50k` to `500`
- Massive scenario will be analyzed in the performance tests

test: reduce integration test payment position size

---

README.md
openapi/openapi.json
src/main/java/it/gov/pagopa/gpd/upload/controller/FileUploadController.java
src/main/java/it/gov/pagopa/gpd/upload/controller/UploadStatusController.java
src/main/java/it/gov/pagopa/gpd/upload/model/UploadInput.java
src/main/java/it/gov/pagopa/gpd/upload/model/UploadOperation.java
src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/test/java/it/gov/pagopa/gpd/upload/controller/FileUploadControllerTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/UploadServiceTest.java

-  add UPDATE API
- update CREATE API business logic
- refactoring API (from 1 to 2 API groups)
- new feature needs: _Massive Update through file upload_
- JUnit test
- Local testing (`gpd-upload-function`, `gpd-core`)

feat: massive update [PAGOPA-1588]

---

openapi/openapi.json
src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/test/java/it/gov/pagopa/gpd/upload/controller/FileUploadControllerTest.java

Fix `Zip Slip` and `Local information disclosure in a temporary directory`
more info:
https://github.com/pagopa/pagopa-gpd-upload/security/code-scanning/72
https://github.com/pagopa/pagopa-gpd-upload/security/code-scanning/73
OWASP: [Path Traversal](https://owasp.org/www-community/attacks/Path_Traversal)
OWASP: [Insecure Temporary File](https://owasp.org/www-community/vulnerabilities/Insecure_Temporary_File)
Code scanning result

chore: fix vulnerability Zip Slip

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionModel.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/main/java/it/gov/pagopa/gpd/upload/utils/GPDValidator.java

- Use a temporary file for the `UploadInput` and `MultipleIUPD` models: serialize this object to a file and upload it via blob block uploading.
- Adjust helm values for PROD deploy

refactoring: update upload input file generation [PAGOPA-1324]

---

helm/values-prod.yaml

[PAGOPA-1702] update key vault name

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/config/RequestFilter.java

- Filter out `/info` path request log
- Reduce noise log

chore: Filter out info path log [PAGOPA-1595] 

---

README.md

Add integration test status badge

feat(README.md): Add status badge

---

Dockerfile
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

- Update Dockerfile: 
- Ensuring that the application running inside the Docker container doesn't have unnecessary permissions

ci: Update Dockerfile

---

.github/workflows/code_review.yml
.github/workflows/deploy_with_github_runner.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
performance-test/src/main_scenario.js
performance-test/yarn/data.js
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/controller/UploadStatusController.java
src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
src/main/java/it/gov/pagopa/gpd/upload/model/UploadReport.java
src/main/java/it/gov/pagopa/gpd/upload/model/pd/MultipleIUPDModel.java
src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentPositionsModel.java
src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
src/main/java/it/gov/pagopa/gpd/upload/utils/GPDValidator.java

- Get report retrieve if doesn't exists as Status on cosmos-db
- Fix performance test
- Set `PaymentPosition` and `IUPDs` `minSize` to 1 (avoid files upload with zero PP)
- Allow the retrieve of the report after it has been deleted as Status from the database (Status time to live)
CosmosPatchOperation application can be found here:
- https://github.com/pagopa/pagopa-gpd-upload-function/pull/20
- https://github.com/pagopa/pagopa-gpd-upload-function/pull/22

chore: [PAGOPA-1787] Update upload report mapping

---

webinar/.env.sample
webinar/PaymentPositions.json
webinar/PaymentPositionsID.json
webinar/requirements.txt
webinar/webinar.ipynb

- Jupyter Notebook on GPD-Massive webinar has been added
- Share webinar stuffs and references with community

[PAGOPA] feat(webinar): Add ipynb stuffs

---

Dockerfile
docker/applicationinsights.json
docker/docker-compose.yml
docker/run_docker.sh
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/config/LogAspect.java
src/main/java/it/gov/pagopa/gpd/upload/config/RequestFilter.java
src/main/java/it/gov/pagopa/gpd/upload/controller/FileUploadController.java
src/main/java/it/gov/pagopa/gpd/upload/exception/ErrorHandler.java
src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
src/main/java/it/gov/pagopa/gpd/upload/utils/GPDValidator.java

chore(logging): update dockerfile + remove useless info logs

---

.github/workflows/update_code.yml

update java-version from 11 to 17 on jobs setup for Micronaut 4.x
[PIDM-491](https://pagopa.atlassian.net/browse/PIDM-491)
[PIDM-491]: https://pagopa.atlassian.net/browse/PIDM-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PIDM-491]: update java-version from 11 to 17 on jobs setup

---

.github/workflows/update_code.yml

jdk update on Github workflow
[PIDM-491](https://pagopa.atlassian.net/browse/PIDM-491)
- [X ] Bug fix (non-breaking change which fixes an issue)
[PIDM-491]: https://pagopa.atlassian.net/browse/PIDM-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PIDM-491]: jdk update

---

src/main/java/it/gov/pagopa/gpd/upload/model/pd/PaymentOptionModel.java
src/main/java/it/gov/pagopa/gpd/upload/model/pd/TransferModel.java

- Added validation annotation `@Min(value=1L)` to the `amount` property of `TransferModel`, `PaymentOptionModel`
[PIDM-700](https://pagopa.atlassian.net/browse/PIDM-700)
[PIDM-700]: https://pagopa.atlassian.net/browse/PIDM-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [PIDM-700] PaymentOptionModel & TransferModel amount cannot be zero

---

.github/workflows/integration_test.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/config/.env.dev
integration-test/src/config/.env.uat
integration-test/src/step_definitions/support/steps.js
openapi/openapi-support-internal.json
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/Application.java
src/main/java/it/gov/pagopa/gpd/upload/controller/external/FileUploadController.java
src/main/java/it/gov/pagopa/gpd/upload/controller/external/UploadStatusController.java
src/main/java/it/gov/pagopa/gpd/upload/controller/support/SupportController.java
src/main/java/it/gov/pagopa/gpd/upload/entity/Status.java
src/main/java/it/gov/pagopa/gpd/upload/entity/Upload.java
src/main/java/it/gov/pagopa/gpd/upload/model/enumeration/ServiceType.java
src/main/java/it/gov/pagopa/gpd/upload/repository/BlobStorageRepository.java
src/main/java/it/gov/pagopa/gpd/upload/repository/FileRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/BlobService.java
src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
src/test/java/it/gov/pagopa/gpd/upload/controller/FileUploadControllerTest.java
src/test/java/it/gov/pagopa/gpd/upload/controller/SupportControllerTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/StatusServiceTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/UploadServiceTest.java

- Added new query param `serviceType` to all APIs
- Added metadata `serviceType` to blob saved on storage
- Added param `serviceType` to message sent on queue
- Updated unit tests
- Updated openapi
- Updated integration test with ACA url
[PAGOPA-3220](https://pagopa.atlassian.net/browse/PAGOPA-3220)
[PAGOPA-3220]: https://pagopa.atlassian.net/browse/PAGOPA-3220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [PAGOPA-3220] ACA massive upload

---

.github/workflows/integration_test.yml
.github/workflows/release_deploy.yml
.identity/00_data.tf
.identity/03_github_environment.tf

chore: [PAGOPA-3216] Identity

---

.github/workflows/release_deploy.yml

- Added `if` to `create new release` step in deploy GHA
GHA was creating new releases unnecessarily, causing failures because the tag already existed

fix: GHA release & deploy skip not working

---

openapi/openapi-internal-support.json
openapi/openapi-v1.json
openapi/openapi-v2.json

fix: Generated openapi

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

- added rolling update strategy (maxUnavailable, maxSurge)
- overridden deployment replicas to match HPA minReplica config
This change is required so the pod replicas are set to match the autoscaling config during deploy, to avoid starting the service with 1 pod when there is traffic on the service

feat: [PIDM-504] update deploy config and strategy

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi-internal-support.json
openapi/openapi-v1.json
openapi/openapi-v2.json
pom.xml
src/main/java/it/gov/pagopa/gpd/upload/controller/support/SupportController.java
src/main/java/it/gov/pagopa/gpd/upload/repository/StatusRepository.java
src/main/java/it/gov/pagopa/gpd/upload/service/SlackService.java
src/main/java/it/gov/pagopa/gpd/upload/service/StatusService.java
src/main/java/it/gov/pagopa/gpd/upload/service/SupportService.java
src/main/java/it/gov/pagopa/gpd/upload/utils/CommonCheck.java
src/main/java/it/gov/pagopa/gpd/upload/utils/SlackNotifier.java
src/main/resources/application.properties
src/test/java/it/gov/pagopa/gpd/upload/controller/SupportControllerTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/SlackServiceTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/SupportServiceGroupingTest.java
src/test/java/it/gov/pagopa/gpd/upload/service/SupportServiceTest.java
src/test/java/it/gov/pagopa/gpd/upload/utils/SlackNotifierTest.java
src/test/java/it/gov/pagopa/gpd/upload/utils/TestMockFactory.java

chore: [PAGOPA-3283] Monitoring
